README.md

Qualify both uses of "comprehensive list" with "hosted on GitHub"

Clarify that the "comprehensive list" is just GitHub

---

app/data/projects.json

Reverts RedHatOfficial/RedHatOfficial.github.io#83

Revert "Update projects.json"

---

app/data/projects.json

Add the KubeVirt project to projects.json.

Add KubeVirt to projects.json

---

app/data/projects.json

Add ManageIQ Exchange Project

---

app/data/projects.json

Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>

Added Tuned project

---

app/data/projects.json

Used by Infinispan developers and QA

Add RadarGun

---

app/data/projects.json

Signed-off-by: Sachin Patil <psachin@redhat.com>

Add Red Hat Insights

---

app/data/projects.json

Added Kubernetes.io

---

app/data/projects.json

Crash utility seems to meet the criteria.  Not sure whether it should be "Development" or "Platform",
but since kpatch is Development, that seems to be the closest package type.

Add crash utility

---

app/data/projects.json

I am not sure what Category is correct here. See #42

Add .NET Core

---

app/data/projects.json

Remove Almighty

---

app/data/projects.json

Red Hat is among the top contributors to Linux, of course.

Add Linux!

---

app/data/projects.json

Updated Minishift project information.
Really not sure why it was under "operations" category but Minishift has been used for the development purpose.

Updated Minishift

---

app/data/projects.json

Both are prominent in https://community.redhat.com/software/, so add them and their GitHub mirrors here.

Add GNOME and LibreOffice

---

app/data/projects.json

Description comes from README.md

Add the Avocado testing framework

---

app/data/projects.json

This adds krb5, mod_auth_gssapi, and the python-gssapi project.

Add my Kerberos stuff

---

app/data/projects.json

Signed-off-by: Peter Jones <pjones@redhat.com>

Add a pile of projects from the Red Hat bootloader team.

---

app/data/projects.json

Red Hat has 4 Python core developers and a Python team who contribute to Python.

Adding Python Project

---

README.md

This helps with the flow of information coming from the previous
paragraph.

move "Built with" section to end of README.md

---

app/data/projects.json

Added information for the OpenShift.io development project. Placed after "OpenShift Origin" in projects.json to help maintain alphabetical order.

Added OpenShift.io project

---

app/data/projects.json

Signed-off-by: sundeep-co-in <suanand@redhat.com>

add transtats project

---

app/data/projects.json

Heketi is a RESTful based volume management framework for Gluster. It is
commonly used in combination with Kubernetes and OpenShift to provide
dynamically allocated storage for apps running in containers.
Signed-off-by: Niels de Vos <ndevos@redhat.com>

Add Heketi to the list of projects

---

.gitignore
app/components/card/card.scss
app/components/dynamictable/dynamictable.scss
app/components/hero/hero.scss
app/components/navigation/navigation.scss
app/components/universalfooter/universalfooter.html
app/components/universalfooter/universalfooter.scss
app/data/featured.json
app/pages/main/main.js
app/pages/main/main.scss
app/public/styles/extends/copy.scss
app/public/styles/global.scss

In this PR, I updated the styles to be mobile-friendly for the hero, table, and footer.  I also fixed a broken image reference pointing to a jpg file that was actually a png.

Add mobile styles, fix broken image

---

app/data/projects.json

adding AI CoE at  https://github.com/AICoE
cc @goern @fridex @t0ffel @vpavlin

add AI CoE

---

app/data/projects.json

Beaker project is a PnT DevOps upstream project for managing and automating labs
of test computers.

Add Beaker project to list of community projects

---

app/data/projects.json

- projectName, projectDescription, projectRepository, and category.
- Would prefer to have a Continuous Integration category.

Add project CentOS CI to the list of community projects

---

app/data/projects.json

Participants:
Miroslav Vadkerti - Platform QE / OSCI
Miloš Prchlík - BaseOS QE
Ondřej Pták - BaseOS QE
Martin Klusoň - BaseOS QE
Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

Add gluetool to the project listing

---

.travis.yml

Issue #106 
With this your site is uploaded each time a PR is merged in dev.
You need to set in travis a environment called: GH_PAGES_TOKEN with a token with access and push to master.

Automate update web

---

app/data/projects.json

added OpenShift Origin to Containers section

Update projects.json with OpenShift Origin

---

app/data/projects.json

Proposed change to resolve https://github.com/RedHatOfficial/RedHatOfficial.github.io/issues/145
Additionally considering:
> ---------- Forwarded message ----------
> Date: Thu, Mar 29, 2018 at 12:03 PM
> ...
> The criteria for listing is any project *and* sub-project that you work on as part of your job at Red Hat.
Thanks,
MM

Enlist Drools, OptaPlanner, jBPM

---

app/data/projects.json

VMaaS is a new project which provides vulnerability management as a service which is consumed by Red Hat Insights.

Add VMaaS project

---

app/data/projects.json

Added Charlotte to the list

---

app/data/projects.json

Remove Drupal

---

app/data/projects.json

Solenopsis is the deployment tool that CE&E created and uses to deploy code to Salesforce

Add Solenopsis project

---

app/data/projects.json

With community.redhat.com/software updates

Update projects.json 

---

app/data/projects.json

Completing the alignment with community.redhat.com/software

Update projects.json again

---

app/data/projects.json

Add projects from the BaseOS Security QE team

Secruity QE projects

---

app/data/projects.json

The RADAnalyatics team (already listed in the projects) also contributes to Apache Spark. I added in the list to make this visible.

Add Apache Spark in the project list

---

app/data/projects.json

Add upgrade tooling projects

---

app/data/projects.json

Please let me know if there's anything else that needs to happen to get this updated! Much appreciated :)

Update to reflect current location of Snowdrop website

---

app/data/projects.json

Teiid has migrated from https://teiid.jboss.org/ to https://teiid.io/

updating projects.json with new URL for Teiid

---

app/data/projects.json

- The repo and website have moved.
- The project's mission has expanded beyond Labs and Red Hat.
Thank you!! :smile:

Update Open Practice Library location

---

app/data/projects.json

As a developer involved in both projects, I'd like to see them removed, as they are not being actively maintained anymore.
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

Spring Cleaning - Removed Hawkular and GateIn

---

app/data/projects.json

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

Added project website for Kiali

---

app/components/universalfooter/universalfooter.html
app/components/universalfooter/universalfooter.js

I noticed that the year on the website is outdated. So I figured that maybe it's worth making it dynamic...

🎨 Update the copyright year to be dynamic

---

app/data/projects.json

Updated website for 3scale per issue #210

Updated 3scale website

---

app/data/projects.json

Added Quay

---

app/data/projects.json

Update to project list to include podman and the website for buildah

Add podman

---

app/components/card/card.html
app/components/card/card.scss
app/data/featured.json
package.json

For the featured projects, I have added twitter links.
The current UI looks this:
I have updated the UI to:

Added twitter link

---

README.md

Updated Readme.md : Changes made as per a Suggestion. 
@castastrophe  Fixes PR #238  and issue #233

Updated Readme.md as per as suggested changes.

---

app/data/projects.json

This is a community of practice, so seemed to fit cleanly into the Organizations category.

Adding The Open Source Way

---

app/data/projects.json

Adding Knative as it has a lot of RH contributors. OpenShift Serverless product is based on it.

Add a Knative

---

app/components/dynamictable/dynamictable.html
app/components/dynamictable/dynamictable.js

- (#253) Update how the list is alphabetized to ignore "The" at the beginning of a project

Closes #253: Update alphabetization to ignore the

---

app/data/projects.json

This adds Red Hat's Maistra Service Mesh to the website. 

Add Maistra

---

README.md
app/components/dynamictable/dynamictable.html
app/components/dynamictable/dynamictable.scss
app/data/projects.json
package-lock.json
package.json

Added a twitter column and tweaked some of the table's styling to be as similar as I could to its original style. Let me know if there are any changes I can make. Also added twitter handle and link spaces to the projects on projects.json for if/when they want to be added. Used Ansible as an example and placed its twitter info.

Addition of twitter column

---

app/data/projects.json

- (#100) Description
1. 
Your updates should work in the following environments:
Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

Change jbosstm to Narayana and it's description and the website

---

app/components/hero/hero.scss

- (#89) Reduce hero padding
1. [Preview netlify build](https://deploy-preview-271--red-hat.netlify.app/#!/main)
Your updates should work in the following environments:
Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

#89: Reduce padding on hero

---

app/data/projects.json

Add Red Hat Product Security to list of projects

---

app/data/projects.json

This PR updates the link for the AsciiBinder project website. We are linking to the .org domain while the correct page is on the .net domain.
- (#288) The link for the AsciiBinder project is wrong.
1. Navigate to the AsciiBinder [GitHub repository](https://github.com/redhataccess/ascii_binder)
2. Verify that the URL listed in the *About* section matches the link updated in the PR.
Your updates should work in the following environments:
Looks like it's a minor change and I can only verify on Firefox on Fedora & RHEL.
Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

fix: correct link to AsciiBinder project

---

app/data/projects.json

Add Linux System Roles to Red Hat official github project list. 
1. Linux-system-roles is found in the project list. And it is found by clicking the SEARCH button.
Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

Add Linux System Roles
